import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import IPhoneFrame from '@/components/iphone-frame';
import Image from 'next/image';
import { GithubIcon } from 'lucide-react';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col items-center justify-items-center h-screen p-8 gap-16 sm:p-12 font-[family-name:var(--font-geist-sans)]">
          <main className="flex flex-col">
            <IPhoneFrame>{children}</IPhoneFrame>
          </main>
          <footer className="flex gap-6 flex-wrap items-center justify-center">
            <a
              className="flex items-center gap-2 hover:underline hover:underline-offset-4"
              href="https://github.com/siisee11/-e-tutor"
              target="_blank"
              rel="noopener noreferrer"
            >
              <GithubIcon className="w-4 h-4" />
              Github →
            </a>
          </footer>
        </div>
      </body>
    </html>
  );
}
